### ISSUE TITLE
Closing window and rerunning glscreen broken

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGL/GLVisualize.jl#36]
Running the following, then closing the window, then running again gives an error:

```julia
using ApproxFun,GLVisualize
w,render=glscreen()

f=ProductFun((x,y)->exp(-x^2-y^2))
x=map(Float32,points(f,1))
y=map(Float32,points(f,2))
z=map(Float32,values(f))

view(visualize(x, y, z, :surface))
render()
```

```julia
ERROR: Named attribute (:vertices) is not an active attribute in the specified program object or

            the name starts with the reserved prefix gl_

 in get_attribute_location at /Users/solver/.julia/v0.4/GLAbstraction/src/GLExtendedFunctions.jl:30
 in call at /Users/solver/.julia/v0.4/GLAbstraction/src/GLTypes.jl:116
 in call at /Users/solver/.julia/v0.4/GLAbstraction/src/GLTypes.jl:155
 in instanced_renderobject at /Users/solver/.julia/v0.4/GLAbstraction/src/GLRenderObject.jl:30
 in assemble_instanced at /Users/solver/.julia/v0.4/GLVisualize/src/utils.jl:71
 in visualize at /Users/solver/.julia/v0.4/GLVisualize/src/visualize/surface.jl:69
 in visualize at /Users/solver/.julia/v0.4/GLVisualize/src/visualize/surface.jl:52
```

**Comment by SimonDanisch** [comment]
This is a long known bug, which had low priority since I never felt like it's a very important use case.
You can just do empty!(w.renderlist) for example, or restart Julia.
I do see that it's not that satisfying ;)
Bad news is, that I thought I knew what the error was, but after looking into this, it turned out I that I don't know what the problem is...
I'll investigate!

**Comment by SimonDanisch** [comment]
Found it already! Obviously, I didn't clean up the cache of the compiled shaders correctly....
I'll fix it on master tomorrow!

**Comment by SimonDanisch** [comment]
Okay, this should be fixed! :)
Best,
Simon

**Comment by SimonDanisch** [comment]
Available after:
`Pkg.checkout("GLVisualize");Pkg.checkout("GLAbstraction")`

**Comment by dlfivefifty** [comment]
Great!

	Have you played around with Plots.jl yet?  It’s really nice for 2D plotting.  I’m thinking of adding GLVisualize as a pull request for that.

**Comment by tbreloff** [comment]
Yes please! You can start a new backend by copying src/backends/template.jl and adding the relevant stuff to src/plotter.jl. I've been wanting to link GLVisualize for a while but haven't gotten around to learning how it works. Start an issue with any questions. 

Also... I'm starting to get better 3D support so you'll be able to do a lot right away. For example, the Plotly backend has 3D scatter, path, contour, and surfaces.

**Comment by dlfivefifty** [comment]
I’m still getting errors

julia> using GLVisualize

julia> w,render=glscreen();
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0

julia> render();
Nov 25 11:56:37  julia[41421] <Warning>: void CGSUpdateManager::log() const: conn 0x313af: spurious update.

julia> render();
ERROR: Library == CNULL. FreeTypeAbstraction.done() called before init(), or done called two times?
 in FreeTypeAbstraction_done at /Users/solver/.julia/v0.4/GLVisualize/src/FreeTypeAbstraction.jl:45
 in renderloop at /Users/solver/.julia/v0.4/GLVisualize/src/display/renderloop.jl:137
 in renderloop_fun at /Users/solver/.julia/v0.4/GLVisualize/src/display/renderloop.jl:123 (repeats 2 times)

julia> w,render=glscreen();
ERROR: initialization failed
 in Init at /Users/solver/.julia/v0.4/GLFW/src/glfw3.jl:308
 in glscreen at /Users/solver/.julia/v0.4/GLVisualize/src/display/renderloop.jl:95

**Comment by SimonDanisch** [comment]
hm... `CGSUpdateManager::log()` sounds like a GLFW problem on OSX.
Can you try:
```Julia
using GLVisualize
w,r = glscreen()
render()
#close window
w,r = glscreen()
render()
```
it's definitely wrong to call render after the window is closed. It's a statefull closure, specific to that one window, which is why it gets returned ;)

**Comment by dlfivefifty** [comment]
OK That works!  Thought I tried it too, but guess not

**Comment by dlfivefifty** [comment]
Here’s another broken version.  What if I want to create two different screens at the same time?




julia> using GLVisualize

julia> w,render=glscreen();
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0

julia> w,render=glscreen();
ERROR: Named attribute (:texturecoordinates) is not an active attribute in the specified program object or

            the name starts with the reserved prefix gl_

 in get_attribute_location at /Users/solver/.julia/v0.4/GLAbstraction/src/GLExtendedFunctions.jl:30
 in call at /Users/solver/.julia/v0.4/GLAbstraction/src/GLTypes.jl:116
 in call at /Users/solver/.julia/v0.4/GLAbstraction/src/GLTypes.jl:155
 in std_renderobject at /Users/solver/.julia/v0.4/GLAbstraction/src/GLRenderObject.jl:44
 in assemble_std at /Users/solver/.julia/v0.4/GLVisualize/src/utils.jl:66
 in postprocess at /Users/solver/.julia/v0.4/GLVisualize/src/display/renderloop.jl:48
 in glscreen at /Users/solver/.julia/v0.4/GLVisualize/src/display/renderloop.jl:108

**Comment by SimonDanisch** [comment]
The whole architecture is not really made for this yet. It's surprisingly difficult to use OpenGL with different windows. It is on my list but requires relatively drastic changes to ModernGL, GLWindow and GLAbstraction.
Would it be okay to have different screens in one window? That already works:
```Julia
using GLVisualize, Reactive, GeometryTypes, GLWindow, GLAbstraction
 
w,r = glscreen()
xhalf(r)    = Rectangle(r.x,r.y, r.w÷2, r.h)
xhalf2(r)   = Rectangle(r.w÷2, r.y, r.w÷2, r.h)
const screen3D = Screen(w, area=const_lift(xhalf, w.area))
const screen2D = Screen(w, area=const_lift(xhalf2, w.area))
view(visualize(rand(Float32, 10,10)), screen3D)
view(visualize([rand(Point2f0)*1000 for i=1:50]), screen2D)
r()
```

**Comment by SimonDanisch** [comment]
![image](https://cloud.githubusercontent.com/assets/1010467/11411441/55b8ff10-93d0-11e5-82de-bb005e04b2aa.png)

**Comment by dlfivefifty** [comment]
OK, in the context of Plots, maybe  “plot" will close the previous window and open a new one, and “subplot” will do what you show here.

**Comment by SimonDanisch** [comment]
Couldn't `plot(...)` just call `empty!(window.renderlist)`, instead of closing the window?

**Comment by dlfivefifty** [comment]
I suppose it could get access to window by calling current() to get the current plot, and therefore access to window.   There may be some added difficulty in handling the first time when the window has to be setup.
