### ISSUE TITLE
bug in 2d visualization

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGL/GLVisualize.jl#46]
I obtain a weird result when trying to visualize multiple 2d points, as in
```julia
    w, r = glscreen()
    s = Vec2f0(100)
    N = 10
    points = Point2f0[rand(Point2f0, -10f0:eps(Float32):10f0) for x=1:N]
    # points = Point2f0[Point2f0(x,0f0) for x=-10f0:0.1f0:10f0]
    v = visualize(points, scale=s)
    view(v)
    r()
```
The resulting render is a single point in the bottom left corner of the window:
![glvisualize_001](https://cloud.githubusercontent.com/assets/7014210/11762341/85d0968e-a0e3-11e5-8658-98e81bf22965.png)

The same happens when running the testsuite, except for two cases,
```julia
push!(TEST_DATA2D, visualize(particle_robj[:positions], scale=s, color=particle_color, style=Cint(OUTLINED), shape=Cint(ROUNDED_RECTANGLE)))
```
and
```julia
curve_data(i) = Point2f0[Point2f0(sin(x/i)*250, x) for x=1:1024]
push!(TEST_DATA2D, visualize(const_lift(curve_data, bounce(20f0:0.1f0:1024f0)), :lines))
```
which are displayed correctly

Cheers,
Carlo

**Comment by SimonDanisch** [comment]
Well this is osrt of to expected, since the units are in pixels.
Have you tried `rand(Point2f0, -500f0:eps(Float32):500f0)` ?
It should be okay in the testsuite, though. Can you attach a screenshot?

**Comment by CarloLucibello** [comment]
thank you for helping out

>Have you tried rand(Point2f0, -500f0:eps(Float32):500f0) ?
 
the same happens

Here is tests' screenshot, see those empty spaces
![glvisualize_002](https://cloud.githubusercontent.com/assets/7014210/11762712/2f1c8598-a0f0-11e5-81e5-4bb53b73ed11.png)

How do you translate the camera btw? I can only rotate and zoom

**Comment by SimonDanisch** [comment]
Oh wait, I think I've seen that bug.
Can you try to replace the call to `glscreen` with this:
```Julia
w,r = glscreen(debugging=true)
```
Also, this might be fixed in the `next2` branch.
If you wish, I can look what packages you will need to checkout.
It should be somethin like:
```Julia
Pkg.checkout("GLVisualize", "next2")
Pkg.checkout("GLAbstraction", "sd/next²")
Pkg.checkout("GeometryTypes", "sd/typealias")
Pkg.checkout("FixedSizeArrays")
Pkg.checkout("GLWindow")
```

**Comment by SimonDanisch** [comment]
The middle mouse button gives you translate... I'll need to rework the camera, since a lot of people don't actually use a mouse with a middle button...

**Comment by CarloLucibello** [comment]
I tried the debugging option but it didń't print any additional information

on the branch next2 my script yelds this
![glvisualize_002](https://cloud.githubusercontent.com/assets/7014210/11766808/6e19ce2a-a197-11e5-94f0-b134591eb525.png)

**Comment by SimonDanisch** [comment]
Can you try runtest.jl?

**Comment by CarloLucibello** [comment]
![glvisualize_003](https://cloud.githubusercontent.com/assets/7014210/11767422/2ba4306a-a1ad-11e5-97c3-b5a0c9055ddf.png)

**Comment by SimonDanisch** [comment]
Great, this looks like it should be fixed :)
Try
```Julia
using GLVisualize, GeometryTypes
w, r = glscreen()
s = Vec2f0(100)
N = 10
points = Point2f0[Point2f0(x,0f0) for x=linspace(0, N*s[1], N)]
v = visualize(points, scale=s)
#v = visualize((Circle(Point2f0(0), scale[1]), points))
view(v, method=:orthographic_pixel) #it's actually a bug that you need to define the method.
r()
```

**Comment by CarloLucibello** [comment]
nice, it works!

**Comment by SimonDanisch** [comment]
Awesome, thanks for trying this out! I'll leave this open until `next2` is merged!

**Comment by kleinash** [comment]
Hi - is this still open? I get an error when running the test:

ERROR: LoadError: ArgumentError: StructsOfArrays not found in path

I am rendering in a loop and would like to clear the screen re-rendering in the same window, is there an easy way to do that? Because with every render the loop slows.

**Comment by SimonDanisch** [comment]
So are you on the next branch?
I've updated the README in that branch. It now contains all the packages you need.
Note, that I just pushed some changes to the ArraysOfStructs fork, which are not compatible yet -.- 
You need to be on this commit:
https://github.com/simonster/StructsOfArrays.jl/pull/3
https://github.com/SimonDanisch/StructsOfArrays.jl/commit/333e5f58e08e8cf0b57ce51ac9e0b23d6f40b4d7

**Comment by kleinash** [comment]
I need the sd/screenbuffer so have just been merging with master. But the change in the README.md causes a conflict. When I am on either branch of GLVisualize Pkg.test("GLVisualize") gives me this:

julia> Pkg.test("GLVisulize")
ERROR: GLVisulize did not provide a test/runtests.jl file

When I run 
$ julia all_tests.jl 
on any branch I get 

surface
ERROR: LoadError: UndefVarError: TEST_DATA not defined


I was just running the test file out of interest, to make sure everything was working. But my origional quest was just to find a way to clear the window before rerunning my loop. 

I dont want to bog you down with stuff thats not that important, although it would be nice to fix what the problem is - what branch should I be on?

**Comment by kleinash** [comment]
Which branch should I be on? I am a little further along with the test something about << not being a unary operator - but I put this on another issue..

**Comment by SimonDanisch** [comment]
I fixed the StructsOfArray thing, so you should be able to simply be on what the readme in next2 says:
https://github.com/JuliaGL/GLVisualize.jl/tree/next2 (If you don't want to be on the tagged version)...

**Comment by SimonDanisch** [comment]
This should also include the screenshot function.. It got moved to GLWindow though: https://github.com/JuliaGL/GLWindow.jl/blob/sd/rebuild/src/screen.jl#L231

**Comment by kleinash** [comment]
Ok.. 

Following the above, my branches are as expected in the list https://github.com/JuliaGL/GLVisualize.jl/tree/next2. Not too worried about version, just as long as everything works :) 

I did however run into a snag with glscreen()

LoadError: ArgumentError: function glscreen does not accept keyword arguments
from: 
```julia
w, r = glscreen(resolution = (width, height)); 
```

I see that now you call it using Screen, so I have:

```julia 
w, r = Screen(resolution = (width, height));
 ```

and I get the error 

WARNING: program 1 not linked. Error in: 
~/.julia/v0.4/GLWindow/src/fxaa.vert or
~/.julia/v0.4/GLWindow/src/fxaa.frag or
~/.julia/v0.4/GLWindow/src/fxaa_combine.frag

LoadError: Named attribute (:texturecoordinates) is not an active attribute in the specified program object or

            the name starts with the reserved prefix gl_

while loading In[15], in expression starting on line 27

 in get_attribute_location at /home/ashley/.julia/v0.4/GLAbstraction/src/GLExtendedFunctions.jl:30
 in call at ~/.julia/v0.4/GLAbstraction/src/GLTypes.jl:154
 in call at ~/.julia/v0.4/GLAbstraction/src/GLTypes.jl:216
 in postprocess at ~/.julia/v0.4/GLWindow/src/types.jl:32
 in call at ~/.julia/v0.4/GLWindow/src/types.jl:55
 in Screen at ~/.julia/v0.4/GLWindow/src/screen.jl:272
 in Screen at ~/.julia/v0.4/GLWindow/src/screen.jl:237


Running it again not changing anything I get:

LoadError: MethodError: `start` has no method matching start(::GLWindow.Screen)
while loading In[2], in expression starting on line 27

So I swapped back to sd/screenbuffer (from next2) and its giving me:

LoadError: UndefVarError: createwindow not defined 

So all in all everything seems like its not working.. And I am really sorry to be the bearer or bad news not knowing enough to go and fix it myself.. 

Am I on the right issue? should we move this somewhere else?

**Comment by SimonDanisch** [comment]
You're not on the right issue, if you actually try to get next2 running in order to get the point rendering running.

`LoadError: MethodError: start has no method matching start(::GLWindow.Screen)` 

This is to be expected, if you haven't changed your example code in this way:
```
# old API
window, renderloop = glscreen()

# new API
window = glscreen()

GLWindow.renderloop(window) # renderloop is also exported by GLVisualize
```

**Comment by kleinash** [comment]
Hi,

I am still getting errors, most likely to do with my understanding of the syntax. Going back to your examples - how do these change with the new methods:

https://github.com/JuliaGL/GLVisualize.jl/blob/master/examples/camera.jl  (I have looked at https://github.com/JuliaGL/GLVisualize.jl/blob/next2/examples/camera/camera2.jl)
https://github.com/JuliaGL/GLVisualize.jl/blob/master/examples/rotate_robj.jl

Like how to I now set my resolution? 

And my errors are going nuts with types..

**Comment by SimonDanisch** [comment]
>And my errors are going nuts with types..

What does that even mean?

Well, I'll very soon release a new suite of examples with videos and comments and everything. Right now I'm actually nearly done with the camera rebuild, so the camera example should be outdated on `next2`. I wouldn't recommend working on the `next2` branch right now!

**Comment by kleinash** [comment]
Ok.. I get that updating things while in progress is not a good idea.. hopefully I can get everything to go back to when it was working.. 

To get to where I am I did this:

Pkg.checkout("GLAbstraction", "sd/next²")
Pkg.checkout("GLVisualize", "next2")
Pkg.checkout("GLWindow", "sd/rebuild")
Pkg.checkout("GeometryTypes", "sd/boundingbox")
Pkg.checkout("FixedSizeArrays", "master")

Now I swapped back to Pkg.checkout("GLVisualize", "sd/screenbuffer")
and I get this error ```LoadError: UndefVarError: createwindow not defined``` when running this line ```w = glscreen()``` and when I go right back to ```w,r=glscreen(resolution = (width, height))``` I get that glscreen does not take arguments and the same createwindow error..

**Comment by SimonDanisch** [comment]
Is there a particular reason why you need to be on the `next2` set of branches? Does the tagged version not work for you?

**Comment by kleinash** [comment]
Nope - was just being pedantic and trying to get the test working.. but I don't need to have my cake and eat it.
