### ISSUE TITLE
template2source method missing

### ISSUE THREAD

**Issue by tknopp** [JuliaGL/GLVisualize.jl#63]
I tried the example for volume rendering from http://www.glvisualize.com/examples/volumes/
and get this error
```
julia> volume = visualize(volumedata, :mip)
ERROR: MethodError: `template2source` has no method matching template2source(::Array{UInt8,1}, ::Dict{Symbol,Any}, ::Dict{Any,Any})
Closest candidates are:
  template2source(::Array{UInt8,1}, ::Dict{Symbol,Any}, ::Dict{ASCIIString,ASCIIString})
  template2source(::AbstractString, ::Dict{Symbol,Any}, ::Dict{ASCIIString,ASCIIString})
 in TemplateProgram at /Users/knopp/.julia/v0.4/GLAbstraction/src/GLShader.jl:257
 in anonymous at /Users/knopp/.julia/v0.4/GLAbstraction/src/GLShader.jl:233
 in const_lift at /Users/knopp/.julia/v0.4/GLAbstraction/src/GLUtils.jl:197
 in TemplateProgram at /Users/knopp/.julia/v0.4/GLAbstraction/src/GLShader.jl:230
 in TemplateProgram at /Users/knopp/.julia/v0.4/GLAbstraction/src/GLShader.jl:215
 in gl_convert at /Users/knopp/.julia/v0.4/GLAbstraction/src/GLShader.jl:195
 in call at /Users/knopp/.julia/v0.4/GLAbstraction/src/GLTypes.jl:245
 in assemble_shader at /Users/knopp/.julia/v0.4/GLVisualize/src/utils.jl:28
```
I pasted the example code to the REPL and you can see the command with the issue is `volume = visualize(volumedata, :mip)`

I had commented out the missing extension as this is on a macbook

**Comment by tknopp** [comment]
This is not on master. Just `Pkg.add...`

**Comment by SimonDanisch** [comment]
Ah, that's a consequence of the fix in #62 ... 
Best is to just comment out all three lines, so that view doesn't get overwritten with an untyped Dict!

**Comment by tknopp** [comment]
done but now the fragment shader is not compiling anymore
```
WARNING: shader /Users/knopp/.julia/v0.4/GLVisualize/src/../assets/shader/volume.frag didn't compile. 
ERROR: 0:181: Unknown identifier 'depth_greater' in layout
```

**Comment by SimonDanisch** [comment]
But `runtests.jl` works ??

**Comment by tknopp** [comment]
no same issue.

**Comment by SimonDanisch** [comment]
Okay... So this didn't fix it :( I'll research tomorrow if Apple offers
this in some other way!
If not, this is only a speed optimization, so I could leave it out for OSX.

2016-02-27 22:54 GMT+01:00 Tobias Knopp <notifications@github.com>:

**Comment by tknopp** [comment]
I close this since it was a side effect issue
